import { Injectable } from '@angular/core';

export class Customer {
  ID: number;
  CompanyName: string;
  Address: string;
  City: string;
  State: string;
  Zipcode: number;
  Phone: string;
  Fax: string;
  Website: string;

  constructor(ID: number, CompanyName: string, Address: string, City: string, State: string, Zipcode: number, Phone: string, Fax: string, Website: string) {
    this.ID = ID;
    this.CompanyName = CompanyName;
    this.Address = Address;
    this.City = City;
    this.State = State;
    this.Zipcode = Zipcode;
    this.Phone = Phone;
    this.Fax = Fax;
    this.Website = Website;
  }
}

let customers: Customer[] = [{
  "ID": 1,
  "CompanyName": "Super Mart of the West",
  "Address": "702 SW 8th Street",
  "City": "Bentonville",
  "State": "Arkansas",
  "Zipcode": 72716,
  "Phone": "(800) 555-2797",
  "Fax": "(800) 555-2171",
  "Website": "http://www.nowebsitesupermart.com"
}, {
  "ID": 2,
  "CompanyName": "Electronics Depot",
  "Address": "2455 Paces Ferry Road NW",
  "City": "Atlanta",
  "State": "Georgia",
  "Zipcode": 30339,
  "Phone": "(800) 595-3232",
  "Fax": "(800) 595-3231",
  "Website": "http://www.nowebsitedepot.com"
}, {
  "ID": 3,
  "CompanyName": "K&S Music",
  "Address": "1000 Nicllet Mall",
  "City": "Minneapolis",
  "State": "Minnesota",
  "Zipcode": 55403,
  "Phone": "(612) 304-6073",
  "Fax": "(612) 304-6074",
  "Website": "http://www.nowebsitemusic.com"
}, {
  "ID": 4,
  "CompanyName": "Tom's Club",
  "Address": "999 Lake Drive",
  "City": "Issaquah",
  "State": "Washington",
  "Zipcode": 98027,
  "Phone": "(800) 955-2292",
  "Fax": "(800) 955-2293",
  "Website": "http://www.nowebsitetomsclub.com"
}, {
  "ID": 5,
  "CompanyName": "E-Mart",
  "Address": "3333 Beverly Rd",
  "City": "Hoffman Estates",
  "State": "Illinois",
  "Zipcode": 60179,
  "Phone": "(847) 286-2500",
  "Fax": "(847) 286-2501",
  "Website": "http://www.nowebsiteemart.com"
}, {
  "ID": 6,
  "CompanyName": "Walters",
  "Address": "200 Wilmot Rd",
  "City": "Deerfield",
  "State": "Illinois",
  "Zipcode": 60015,
  "Phone": "(847) 940-2500",
  "Fax": "(847) 940-2501",
  "Website": "http://www.nowebsitewalters.com"
}, {
  "ID": 7,
  "CompanyName": "StereoShack",
  "Address": "400 Commerce S",
  "City": "Fort Worth",
  "State": "Texas",
  "Zipcode": 76102,
  "Phone": "(817) 820-0741",
  "Fax": "(817) 820-0742",
  "Website": "http://www.nowebsiteshack.com"
}, {
  "ID": 8,
  "CompanyName": "Circuit Town",
  "Address": "2200 Kensington Court",
  "City": "Oak Brook",
  "State": "Illinois",
  "Zipcode": 60523,
  "Phone": "(800) 955-2929",
  "Fax": "(800) 955-9392",
  "Website": "http://www.nowebsitecircuittown.com"
}, {
  "ID": 9,
  "CompanyName": "Premier Buy",
  "Address": "7601 Penn Avenue South",
  "City": "Richfield",
  "State": "Minnesota",
  "Zipcode": 55423,
  "Phone": "(612) 291-1000",
  "Fax": "(612) 291-2001",
  "Website": "http://www.nowebsitepremierbuy.com"
}, {
  "ID": 10,
  "CompanyName": "ElectrixMax",
  "Address": "263 Shuman Blvd",
  "City": "Naperville",
  "State": "Illinois",
  "Zipcode": 60563,
  "Phone": "(630) 438-7800",
  "Fax": "(630) 438-7801",
  "Website": "http://www.nowebsiteelectrixmax.com"
}, {
  "ID": 11,
  "CompanyName": "Video Emporium",
  "Address": "1201 Elm Street",
  "City": "Dallas",
  "State": "Texas",
  "Zipcode": 75270,
  "Phone": "(214) 854-3000",
  "Fax": "(214) 854-3001",
  "Website": "http://www.nowebsitevideoemporium.com"
}, {
  "ID": 12,
  "CompanyName": "Screen Shop",
  "Address": "1000 Lowes Blvd",
  "City": "Mooresville",
  "State": "North Carolina",
  "Zipcode": 28117,
  "Phone": "(800) 445-6937",
  "Fax": "(800) 445-6938",
  "Website": "http://www.nowebsitescreenshop.com"
}];

@Injectable({
  providedIn: 'root'
})
export class MockDataService {
  fakeData = {
    Departments: [
      {
        CreatedBy: null,
        CreatedDate: "2021-09-23T18:55:01.040+07:00",
        DepartmentID: 26055,
        DepartmentName: "Phòng Quản trị điều hành",
        Description: null,
        DictionaryKey: null,
        EditVersion: null,
        IsSystem: 0,
        ListDepartmentUser: null,
        ListProject: [
          {
            CreatedBy: null,
            CreatedDate: "2021-09-23T18:55:01.036+07:00",
            Description: null,
            DepartmentID: 26055,
            DepartmentName: "Phòng Quản trị điều hành",
            DictionaryKey: null,
            DisplayFontSize: null,
            EditVersion: null,
            EndDate: null,
            HasViewReportProject: true,
            ImageDetail: null,
            IsAllowsSubTasksDiffer: false,
            IsApprovalFinish: null,
            IsArchiveDelete: false,
            IsAutoCompleteTask: false,
            IsAutoProcessTask: false,
            IsCreatedFromProjectTemplate: false,
            IsEditCompleteTask: false,
            IsMyTask: false,
            IsNotAllowEditTaskDone: false,
            IsPersonalDepartmentOther: false,
            IsPrivateProject: null,
            IsProjectArchive: null,
            IsProjectFromTemplate: false,
            IsProjectTemplate: false,
            IsReasonTimeDelay: false,
            IsSaveFromOtherTemplate: false,
            IsSaveTimeDoneTaskApproved: false,
            IsSystem: false,
            Kanbans: null,
            ListUserIDSharedTemplate: null,
            ModifiedBy: null,
            ModifiedDate: "2021-09-23T18:55:01.036+07:00",
            OldData: null,
            OldProjectID: 0,
            OldProjectName: null,
            PassWarningCode: null,
            ProjectID: 9849,
            ProjectName: "MISA Công việc",
            ProjectStatus: 1,
            ProjectUsers: null,
            Projects: null,
            SettingDisplayTask: null,
            SortOrder: 0,
            StartDate: null,
            State: 0,
            Status: 1,
            StatusApproval: null,
            Tasks: null,
            TemplateDescription: null,
            TenantID: "00000000-0000-0000-0000-000000000000",
            UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
            projectCustomField: null
          }
        ],
        ModifiedBy: null,
        ModifiedDate: "2021-09-23T18:55:01.040+07:00",
        RoleType: 0,
        SortOrder: 1,
        State: 0,
        UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493"
      },
      {
        CreatedBy: null,
        CreatedDate: "2021-09-25T20:53:52.773+07:00",
        DepartmentID: 26063,
        DepartmentName: "Phòng đào tạo",
        Description: null,
        DictionaryKey: null,
        EditVersion: null,
        IsSystem: 0,
        ListDepartmentUser: null,
        ListPermission: "AddProject;AddUserInSystemToDepartment;AddUserNotInSystemToDepartment;FullPermissonAllProjectInDepartment;SettingInfoDepartment;ViewAllProjectInDepartment",
        ListProject: [],
        ModifiedBy: null,
        ModifiedDate: "2021-09-25T20:53:52.773+07:00",
        OldData: null,
        PassWarningCode: null,
        RoleType: 0,
        SortOrder: 2,
        State: 0,
        TenantID: "00000000-0000-0000-0000-000000000000",
        UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493"
      },
      {
        CreatedBy: null,
        CreatedDate: "2021-09-25T20:53:52.773+07:00",
        DepartmentID: 26061,
        DepartmentName: "Phòng quản lý nhân lực ABCXYZ",
        Description: null,
        DictionaryKey: null,
        EditVersion: null,
        IsSystem: 0,
        ListDepartmentUser: null,
        ListPermission: "AddProject;AddUserInSystemToDepartment;AddUserNotInSystemToDepartment;FullPermissonAllProjectInDepartment;SettingInfoDepartment;ViewAllProjectInDepartment",
        ListProject: [
          {
            CreatedBy: null,
            CreatedDate: "2021-09-25T20:53:52.772+07:00",
            DateDeleted: null,
            Decription: null,
            DepartmentID: 26061,
            DepartmentName: "Phòng quản lý nhân lực ABCXYZ",
            DictionaryKey: null,
            DisplayFontSize: null,
            DisplayParentTaskOption: 0,
            DuplicateProjectAction: null,
            DuplicateProjectOption: null,
            DuplicateProjectTaskOption: null,
            EditVersion: null,
            EndDate: null,
            HasViewReportProject: true,
            Icon: "ic_blood_16",
            IconColor: "#2196F3",
            Image: null,
            ImageDetail: null,
            IsAllowsSubTasksDiffer: false,
            IsApprovalFinish: null,
            IsArchiveDelete: false,
            IsAutoCompleteTask: false,
            IsAutoProcessTask: false,
            IsCreatedFromProjectTemplate: false,
            IsEditCompleteTask: false,
            IsMyTask: false,
            IsNotAllowEditTaskDone: false,
            IsPersonalDepartmentOther: false,
            IsPrivateProject: null,
            IsProjectArchive: null,
            IsProjectFromTemplate: false,
            IsProjectTemplate: false,
            IsReasonTimeDelay: false,
            IsSaveFromOtherTemplate: false,
            IsSaveTimeDoneTaskApproved: false,
            IsSystem: false,
            Kanbans: null,
            ListUserIDSharedTemplate: null,
            ModifiedBy: null,
            ModifiedDate: "2021-09-25T20:53:52.772+07:00",
            OldData: null,
            OldProjectID: 0,
            OldProjectName: null,
            PassWarningCode: null,
            ProjectID: 9874,
            ProjectName: "MISA AMIS HRM",
            ProjectStatus: 1,
            ProjectUsers: null,
            Projects: null,
            SettingDisplayTask: null,
            SortOrder: 0,
            StartDate: null,
            State: 0,
            Status: 1,
            StatusApproval: null,
            Tasks: null,
            TemplateDescription: null,
            TenantID: "00000000-0000-0000-0000-000000000000",
            UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
            projectCustomField: null

          }
        ],
        ModifiedBy: null,
        ModifiedDate: "2021-09-25T20:53:52.773+07:00",
        OldData: null,
        PassWarningCode: null,
        RoleType: 0,
        SortOrder: 3,
        State: 0,
        TenantID: "00000000-0000-0000-0000-000000000000",
        UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493"
      }
    ],
    ProjectsPersonal: {
      CreatedBy: null,
      CreatedDate: "2021-09-25T20:53:52.773+07:00",
      DepartmentID: 26053,
      DepartmentName: "Cá nhân",
      Description: null,
      DictionaryKey: 1,
      EditVersion: null,
      IsSystem: 1,
      ListDepartmentUser: null,
      ListPermission: "",
      ListProject: [
        {
          CreatedBy: null,
          CreatedDate: "2021-09-25T20:53:52.772+07:00",
          DateDeleted: null,
          Decription: null,
          DepartmentID: 26053,
          DepartmentName: "Cá nhân",
          DictionaryKey: 1,
          DisplayFontSize: null,
          DisplayParentTaskOption: 0,
          DuplicateProjectAction: null,
          DuplicateProjectOption: null,
          DuplicateProjectTaskOption: null,
          EditVersion: null,
          EndDate: null,
          HasViewReportProject: true,
          Icon: "icon-personal-project",
          IconColor: "#2196F3",
          Image: null,
          ImageDetail: null,
          IsAllowsSubTasksDiffer: false,
          IsApprovalFinish: null,
          IsArchiveDelete: false,
          IsAutoCompleteTask: false,
          IsAutoProcessTask: false,
          IsCreatedFromProjectTemplate: false,
          IsEditCompleteTask: false,
          IsMyTask: false,
          IsNotAllowEditTaskDone: false,
          IsPersonalDepartmentOther: false,
          IsPrivateProject: null,
          IsProjectArchive: null,
          IsProjectFromTemplate: false,
          IsProjectTemplate: false,
          IsReasonTimeDelay: false,
          IsSaveFromOtherTemplate: false,
          IsSaveTimeDoneTaskApproved: false,
          IsSystem: true,
          Kanbans: null,
          ListUserIDSharedTemplate: null,
          ModifiedBy: null,
          ModifiedDate: "2021-09-25T20:53:52.772+07:00",
          OldData: null,
          OldProjectID: 0,
          OldProjectName: null,
          PassWarningCode: null,
          ProjectID: 9847,
          ProjectName: "Công việc cá nhân",
          ProjectStatus: 1,
          ProjectUsers: null,
          Projects: null,
          SettingDisplayTask: null,
          SortOrder: 0,
          StartDate: null,
          State: 0,
          Status: 1,
          StatusApproval: null,
          Tasks: null,
          TemplateDescription: null,
          TenantID: "00000000-0000-0000-0000-000000000000",
          UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
          projectCustomField: null
        }
      ],
      ModifiedBy: null,
      ModifiedDate: "2021-09-25T20:53:52.773+07:00",
      OldData: null,
      PassWarningCode: null,
      RoleType: 0,
      SortOrder: 0,
      State: 0,
      TenantID: "00000000-0000-0000-0000-000000000000",
      UserID: "5f8b04d9-74e0-4749-9d26-96adf25ac493"
    }
  }

  fakeDataTask = [
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 200,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 50,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 100,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: -10,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hook",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 88,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 6,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-10T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 24,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    },
    {
      ActionTypeKanban: null,
      ApprovalFullName: null,
      ApprovalLast: null,
      Approvals: null,
      ApprovalsDetail: null,
      ApprovedDate: null,
      ApprovedUserName: null,
      AssigneeEmail: "minhiq149@gmail.com",
      AssigneeID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssigneeJobPositionName: "Lập trình viên",
      AssigneeName: "Phạm Hải Dương",
      AssignerEmail: "minhiq149@gmail.com",
      AssignerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      AssignerName: "Phạm Hải Dương",
      AsyncID: null,
      Attachments: "[]",
      Automation: 0,
      AutomationKanban: null,
      CheckList: null,
      ChildTaskDoneQuantity: null,
      ChildTaskQuantity: null,
      CloneTranID: "00000000-0000-0000-0000-000000000000",
      CommentQuantity: null,
      CreatedBy: "minhiq149@gmail.com",
      CreatedDate: "2021-09-22T09:08:49.626+07:00",
      CreatedDateExport: null,
      CurrentKanban: null,
      CurrentKanbanSettings: null,
      CurrentProject: null,
      CustomFieldValue: null,
      DateDeleted: null,
      DeleteType: 0,
      DepartmentID: 26061,
      DepartmentName: null,
      Description: null,
      DueDate: null,
      DueDateExport: null,
      EditVersion: "2021-09-23T22:01:13.239+07:00",
      Emergency: null,
      EndDate: "2021-10-24T23:59:59.000+07:00",
      EndDateExport: null,
      EndDateOrder: null,
      FinishDate: null,
      FinishDateExport: null,
      FrontTaskID: null,
      GuidIndex: null,
      IconColor: null,
      ImageAttachmentID: null,
      Important: null,
      InsertLogTime: null,
      IsAllowsSubTasksDiffer: false,
      IsApprovalFinish: null,
      IsDoneCreateTaskChild: null,
      IsDuplicateAssignee: false,
      IsDuplicateCheckList: false,
      IsDuplicateDescription: false,
      IsDuplicateFromProject: false,
      IsDuplicateMarkImportance: false,
      IsDuplicateTag: false,
      IsDuplicateTask: false,
      IsDuplicateTaskAttachment: false,
      IsDuplicateTaskChild: false,
      IsHasAutomationLock: "0",
      IsImportSaveTask: false,
      IsInParent: null,
      IsNotAllowEditTaskDone: false,
      IsParent: false,
      IsRemind: null,
      IsRepeat: false,
      IsSelectDueTime: null,
      IsSelectEndTime: false,
      IsSelectStartTime: null,
      IsSystem: false,
      IsTaskArchive: null,
      IsTaskImport: null,
      KanBanNameParentDuplicate: null,
      KanbanID: 32886,
      KanbanIcon: null,
      KanbanIconColor: null,
      KanbanName: "Cần thực hiện",
      KanbanSortOrder: 3,
      Level: 0,
      Level1ChildTaskCompleteQuantity: null,
      Level1ChildTaskQuantity: null,
      Level2ChildTaskQuantity: null,
      ListApprovedUser: null,
      ListChildTask: null,
      ListElementDuplicate: null,
      ListNotApproveUser: null,
      ListParentDisplayInKanban: null,
      ListPeopleApproval: null,
      ListPeopleApprovalString: null,
      ListSendMailPeopleApproval: null,
      ListSortOrder: null,
      ListStringTaskChilds: null,
      ListTaskActivity: null,
      ListTaskApprovals: null,
      ListTaskComments: null,
      ListTaskPeopleInvolveds: null,
      ListTaskRepeats: null,
      MarkImportance: 0,
      ModifiedBy: "minhiq149@gmail.com",
      ModifiedDate: "2021-09-22T09:08:49.627+07:00",
      MyTaskSortOrder: null,
      OldData: null,
      OldID: 0,
      OldParentID: 0,
      OldProcess: null,
      OwnerEmail: "minhiq149@gmail.com",
      OwnerID: "5f8b04d9-74e0-4749-9d26-96adf25ac493",
      OwnerName: "Phạm Hải Dương",
      ParentID: null,
      ParentName: null,
      ParentTask: null,
      PassWarningCode: null,
      PeopleInvolved: null,
      PeopleInvolvedName: null,
      PercentProgress: 0,
      PermissionTaskAutomationLock: null,
      PermissionUserAutomationLock: null,
      PersonRequire: null,
      PersonRequireID: "00000000-0000-0000-0000-000000000000",
      Process: 45,
      ProcessConvert: null,
      Progress: 0,
      ProjectID: 9874,
      ProjectIDParentDuplicate: 0,
      ProjectIcon: "ic_blood_16",
      ProjectIconColor: "#2196F3",
      ProjectName: "MISA AMIS HRM",
      ProjectStatus: 0,
      ProjectTemplateID: 0,
      RealTimeStart: "2021-09-22T09:12:10.421+07:00",
      RemindTimeBeforeDeadline: null,
      ReminderTime: null,
      ReminderType: null,
      Reminders: null,
      RootID: 0,
      STT: 0,
      SortOrder: 1,
      StartDate: null,
      StartDateExport: null,
      State: 0,
      Status: 1,
      StatusTask: null,
      TagIDs: null,
      TagNames: null,
      Tags: null,
      TagsName: null,
      TaskApprovalID: 0,
      TaskApprovalStatus: null,
      TaskChilds: null,
      TaskChildsDuplicateID: null,
      TaskCloneID: null,
      TaskDependent: null,
      TaskID: 120379,
      TaskIDDuplicate: 0,
      TaskName: "Tìm hiểu Lifecycle Hooks",
      TaskStatus: 1,
      TaskStatusDisplay: null,
      TaskStatusView: null,
      TaskStatusViewDiagram: null,
      TaskStatusViewName: null,
      TaskType: null,
      TenantID: "2086d8d4-d6f3-4c77-a4ff-966aeae19f6b",
      TimeTrackings: null,
      TotalDone: null,
      TotalNotDone: null,
      TutalFile: null,
      TypeWorkRate: null,
      UserDeleted: null,
      Weight: null,
      countTaskReport: null,
      isHasDelayTime: 1,
      listObject: null,
      listSendMailPeopleInvolved: null

    }
  ]

  getCustomers() {
    return this.fakeDataTask;
  }

  getSearchData() {
    return this.fakeData;
  }
}
